[package]
name = "spec-provider"
version = "0.1.0"
edition = "2024"

[dependencies]
spec-api = { path = "spec-api", default-features = false, features = ["server"] }

async-trait = "0.1"
chrono = "0.4.45"
prost-types = "0.14"
tokio = { version = "1.53.1", features = ["full"] }
tonic = "0.14"
uuid = { version = "1.26.1", features = ["v4"] }
