syntax = "proto3";

package spec_provider;

import "google/protobuf/timestamp.proto";

service SpecProvider {
  // Returns either the published spec or the draft with the given id.
  rpc GetSpec(GetSpecRequest) returns (GetSpecResponse);
}

// --- Requests / Responses ---

message GetSpecRequest {
  // UUID of the spec or draft.
  string id = 1;
}

message GetSpecResponse {
  oneof kind {
    Spec published = 1;
    Draft draft = 2;
  }
}

// --- Entities ---

// A published spec.
message Spec {
  string id = 1;
  string title = 2;
  // A short, unique abbreviation for the spec.
  string abbreviation = 3;
  // The latest version (last element) is the current version of the spec.
  repeated Version versions = 4;
}

enum DraftVisibility {
  DRAFT_VISIBILITY_UNSPECIFIED = 0;
  DRAFT_VISIBILITY_PUBLIC = 1;
  DRAFT_VISIBILITY_PRIVATE = 2;
  DRAFT_VISIBILITY_HIDDEN = 3;
}

message Draft {
  string id = 1;
  string title = 2;
  // A short, unique abbreviation for the spec.
  string abbreviation = 3;
  DraftVisibility visibility = 4;
  // The already cut versions. The latest version is the last element.
  repeated Version versions = 5;
  // Patches that will be applied to the next version when cut.
  repeated Patch unversioned_patches = 6;
  repeated Proposal proposals = 7;
}

message Version {
  string id = 1;
  repeated Patch patches = 2;
}

message Patch {
  string id = 1;
  string proposed_by = 2;
  google.protobuf.Timestamp created_at = 3;
  string accepted_by = 4;
  google.protobuf.Timestamp accepted_at = 5;
  string content_uri = 6;
}

enum ProposalStatus {
  PROPOSAL_STATUS_UNSPECIFIED = 0;
  PROPOSAL_STATUS_DRAFT = 1;
  PROPOSAL_STATUS_READY = 2;
}

message Proposal {
  string id = 1;
  string proposed_by = 2;
  google.protobuf.Timestamp created_at = 3;
  google.protobuf.Timestamp last_updated_at = 4;
  ProposalStatus status = 5;
  string content_uri = 6;
}
