[package]
name = "auth-server"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.16.0"
axum = { version = "0.8.9", features = ["macros"] }
base64 = "0.22.1"
fnmock = { git = "https://github.com/jakob-rzeppa/fnmock" }

serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9.34"
serde_urlencoded = "0.7.1"

thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["full"] }
url = "2.5.8"
uuid = { version="1.26.0", features=["v4", "serde"] }

api-macros = { git = "https://github.com/jakob-rzeppa/Auth.git", branch = "main" }
chrono = "0.4.45"
redis = { version = "1.7.0", features = ["tokio-comp"] }
rand = "0.10.3"
